
title: Andrey Glushkov CV
url: 'cv.glushkov.net'
# baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Andrey Glushkov
tagline: R'n'D Expert
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: andrey@glushkov.net
phone: +7 918 510 1713
# website: blog.webjeda.com #do not add http://
linkedin: andreyglushkov
github: andreydrv
twitter: '@andrey_drive'

